dist: trusty
language: java
os: linux
jdk:
  - openjdk8
notifications:
  email:
    - email2dineshkuppan@gmail.com
branches:
  only:
    - master
    - develop

cache:
  directories:
    - "$HOME/.m2"
    -
env:
  global:
    - GPG_DIR="`pwd`/deploy"